
package br.com.apartida.servicos.funcionalidadeservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FuncionalidadeService", targetNamespace = "http://apartida.com.br/servicos/FuncionalidadeService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FuncionalidadeService {


    /**
     * 
     * @param idEmpresa
     * @return
     *     returns java.util.List<br.com.apartida.servicos.funcionalidadeservice.FuncionalidadeDTO>
     * @throws IspoException_Exception
     */
    @WebMethod
    @WebResult(name = "funcionalidades", targetNamespace = "")
    @RequestWrapper(localName = "pesquisarFuncionalidadesEmpresa", targetNamespace = "http://apartida.com.br/servicos/FuncionalidadeService", className = "br.com.apartida.servicos.funcionalidadeservice.InPesquisarPelaEmpresa")
    @ResponseWrapper(localName = "pesquisarFuncionalidadesEmpresaResponse", targetNamespace = "http://apartida.com.br/servicos/FuncionalidadeService", className = "br.com.apartida.servicos.funcionalidadeservice.OutPesquisarFuncionalidades")
    public List<FuncionalidadeDTO> pesquisarFuncionalidadesEmpresa(
        @WebParam(name = "idEmpresa", targetNamespace = "")
        long idEmpresa)
        throws IspoException_Exception
    ;

}
