
package br.com.apartida.servicos.funcionalidadeservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FuncionalidadeService", targetNamespace = "http://apartida.com.br/servicos/FuncionalidadeService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FuncionalidadeService {


    /**
     * 
     * @param inPesquisarFuncionalidadesPlano
     * @return
     *     returns br.com.apartida.servicos.funcionalidadeservice.OutPesquisarFuncionalidadesPlano
     * @throws IspoException_Exception
     */
    @WebMethod
    @WebResult(name = "funcionalidadesMenu", targetNamespace = "http://apartida.com.br/servicos/FuncionalidadeService", partName = "funcionalidadesMenu")
    public OutPesquisarFuncionalidadesPlano pesquisarFuncionalidadesPlanoMenu(
        @WebParam(name = "InPesquisarFuncionalidadesPlano", targetNamespace = "http://apartida.com.br/servicos/FuncionalidadeService", partName = "InPesquisarFuncionalidadesPlano")
        InPesquisarFuncionalidadesPlano inPesquisarFuncionalidadesPlano)
        throws IspoException_Exception
    ;

}
