
package br.com.apartida.servicos.funcionalidadeservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FuncionalidadeService", targetNamespace = "http://apartida.com.br/servicos/FuncionalidadeService", wsdlLocation = "http://74.63.218.158:8080/ISPO-EJB/FuncionalidadeService/FuncionalidadeService?wsdl")
public class FuncionalidadeService_Service
    extends Service
{

    private final static URL FUNCIONALIDADESERVICE_WSDL_LOCATION;
    private final static WebServiceException FUNCIONALIDADESERVICE_EXCEPTION;
    private final static QName FUNCIONALIDADESERVICE_QNAME = new QName("http://apartida.com.br/servicos/FuncionalidadeService", "FuncionalidadeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://74.63.218.158:8080/ISPO-EJB/FuncionalidadeService/FuncionalidadeService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FUNCIONALIDADESERVICE_WSDL_LOCATION = url;
        FUNCIONALIDADESERVICE_EXCEPTION = e;
    }

    public FuncionalidadeService_Service() {
        super(__getWsdlLocation(), FUNCIONALIDADESERVICE_QNAME);
    }

    public FuncionalidadeService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), FUNCIONALIDADESERVICE_QNAME, features);
    }

    public FuncionalidadeService_Service(URL wsdlLocation) {
        super(wsdlLocation, FUNCIONALIDADESERVICE_QNAME);
    }

    public FuncionalidadeService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FUNCIONALIDADESERVICE_QNAME, features);
    }

    public FuncionalidadeService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FuncionalidadeService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FuncionalidadeService
     */
    @WebEndpoint(name = "FuncionalidadeServicePort")
    public FuncionalidadeService getFuncionalidadeServicePort() {
        return super.getPort(new QName("http://apartida.com.br/servicos/FuncionalidadeService", "FuncionalidadeServicePort"), FuncionalidadeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FuncionalidadeService
     */
    @WebEndpoint(name = "FuncionalidadeServicePort")
    public FuncionalidadeService getFuncionalidadeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://apartida.com.br/servicos/FuncionalidadeService", "FuncionalidadeServicePort"), FuncionalidadeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FUNCIONALIDADESERVICE_EXCEPTION!= null) {
            throw FUNCIONALIDADESERVICE_EXCEPTION;
        }
        return FUNCIONALIDADESERVICE_WSDL_LOCATION;
    }

}
