
package br.com.apartida.servicos.perfilservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "IspoException", targetNamespace = "http://apartida.com.br/servicos/PerfilService")
public class IspoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IspoException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public IspoException_Exception(String message, IspoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public IspoException_Exception(String message, IspoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: br.com.apartida.servicos.perfilservice.IspoException
     */
    public IspoException getFaultInfo() {
        return faultInfo;
    }

}
