
package br.com.apartida.servicos.perfilservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PerfilService", targetNamespace = "http://apartida.com.br/servicos/PerfilService", wsdlLocation = "http://74.63.218.158:8080/ISPO-EJB/PerfilService/PerfilService?wsdl")
public class PerfilService_Service
    extends Service
{

    private final static URL PERFILSERVICE_WSDL_LOCATION;
    private final static WebServiceException PERFILSERVICE_EXCEPTION;
    private final static QName PERFILSERVICE_QNAME = new QName("http://apartida.com.br/servicos/PerfilService", "PerfilService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://74.63.218.158:8080/ISPO-EJB/PerfilService/PerfilService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERFILSERVICE_WSDL_LOCATION = url;
        PERFILSERVICE_EXCEPTION = e;
    }

    public PerfilService_Service() {
        super(__getWsdlLocation(), PERFILSERVICE_QNAME);
    }

    public PerfilService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERFILSERVICE_QNAME, features);
    }

    public PerfilService_Service(URL wsdlLocation) {
        super(wsdlLocation, PERFILSERVICE_QNAME);
    }

    public PerfilService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERFILSERVICE_QNAME, features);
    }

    public PerfilService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PerfilService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PerfilService
     */
    @WebEndpoint(name = "PerfilServicePort")
    public PerfilService getPerfilServicePort() {
        return super.getPort(new QName("http://apartida.com.br/servicos/PerfilService", "PerfilServicePort"), PerfilService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PerfilService
     */
    @WebEndpoint(name = "PerfilServicePort")
    public PerfilService getPerfilServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://apartida.com.br/servicos/PerfilService", "PerfilServicePort"), PerfilService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERFILSERVICE_EXCEPTION!= null) {
            throw PERFILSERVICE_EXCEPTION;
        }
        return PERFILSERVICE_WSDL_LOCATION;
    }

}
