
package br.com.apartida.servicos.perfilservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PerfilService", targetNamespace = "http://apartida.com.br/servicos/PerfilService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PerfilService {


    /**
     * 
     * @param inPesquisarPerfis
     * @return
     *     returns br.com.apartida.servicos.perfilservice.OutPesquisarPerfis
     * @throws IspoException_Exception
     */
    @WebMethod
    @WebResult(name = "perfis", targetNamespace = "http://apartida.com.br/servicos/PerfilService", partName = "perfis")
    public OutPesquisarPerfis pesquisarPerfisPelaEmpresa(
        @WebParam(name = "inPesquisarPerfis", targetNamespace = "http://apartida.com.br/servicos/PerfilService", partName = "inPesquisarPerfis")
        InPesquisarPelaEmpresa inPesquisarPerfis)
        throws IspoException_Exception
    ;

}
