
package br.com.isports.clientews.usuarioservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UsuarioService", targetNamespace = "http://isoccer.com.br/servicos/UsuarioService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UsuarioService {


    /**
     * 
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(name = "TotalUsuario", targetNamespace = "")
    @RequestWrapper(localName = "buscarTotalUsuario", targetNamespace = "http://isoccer.com.br/servicos/UsuarioService", className = "br.com.isports.clientews.usuarioservice.BuscarTotalUsuario")
    @ResponseWrapper(localName = "buscarTotalUsuarioResponse", targetNamespace = "http://isoccer.com.br/servicos/UsuarioService", className = "br.com.isports.clientews.usuarioservice.BuscarTotalUsuarioResponse")
    public Integer buscarTotalUsuario();

    /**
     * 
     * @param inValidarUsuario
     * @return
     *     returns br.com.isports.clientews.usuarioservice.OutValidarUsuario
     */
    @WebMethod
    @WebResult(name = "usuarioValido", targetNamespace = "")
    @RequestWrapper(localName = "validarUsuario", targetNamespace = "http://isoccer.com.br/servicos/UsuarioService", className = "br.com.isports.clientews.usuarioservice.ValidarUsuario")
    @ResponseWrapper(localName = "validarUsuarioResponse", targetNamespace = "http://isoccer.com.br/servicos/UsuarioService", className = "br.com.isports.clientews.usuarioservice.ValidarUsuarioResponse")
    public OutValidarUsuario validarUsuario(
        @WebParam(name = "inValidarUsuario", targetNamespace = "")
        InValidarUsuario inValidarUsuario);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "cadastrarUsuario", targetNamespace = "http://isoccer.com.br/servicos/UsuarioService", className = "br.com.isports.clientews.usuarioservice.CadastrarUsuario")
    @ResponseWrapper(localName = "cadastrarUsuarioResponse", targetNamespace = "http://isoccer.com.br/servicos/UsuarioService", className = "br.com.isports.clientews.usuarioservice.CadastrarUsuarioResponse")
    public void cadastrarUsuario();

}
